# Spring Application Details
application:
  name=: ecommerce-company

spring:
  # Caffeine Cache Config
  cache:
    cache-names: prices
    caffeine:
      spec: maximumSize=500,initialCapacity=1000
  jpa:
    hibernate:
      # Disable ORM table creation because of Flyway use
      ddl-auto: none
      jdbc:
        # Use UTC zone
        time_zone: UTC
  flyway:
    locations: classpath:db/migration/h2
    baseline-on-migrate: true
  datasource:
    url: jdbc:h2:mem:${application.name}db
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  # Enabling H2 Console
  h2:
    console:
      enabled: true
  # Profiles
  profiles:
    active: local
# Actuator endpoints that let monitor and interact with the application.
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus